apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hasura.fullname" . }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.hasura.replicaCount }}
  selector:
    matchLabels:
      {{- include "hasura.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.hasura.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 -}}
      {{- end }}
      labels:
        {{- include "hasura.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: hasura
          image: "{{ .Values.hasura.image.repository }}:{{ .Values.hasura.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hasura.image.pullPolicy }}
          {{- if .Values.hasura.command }}
          command: 
            {{- range .Values.hasura.command }}
          - {{ . }}
            {{- end }} 
          {{- end }} 
          {{- if .Values.hasura.args }}
          args: 
            {{- range .Values.hasura.args }}
          - {{ . }}
            {{- end }}  
          {{- end }} 
          ports:
            - name: {{ include "hasura.fullname" . }}
              containerPort: 8080
          env:
          {{- range .Values.hasura.env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
            - name: "ACTION_BASE_URL"
              value: http://{{ include "bdjuno.fullname" . }}:3000
          resources:
            {{- toYaml .Values.hasura.resources | nindent 12 }}
      {{- if .Values.hasura.metricsAdapter.enabled }}
          volumeMounts:
          - name: logs
            mountPath: /tmp/log
        - name: hasura-metric-adapter
          image: "{{ .Values.hasura.metricsAdapter.image.repository }}:{{ .Values.hasura.metricsAdapter.image.tag }}"
          imagePullPolicy: {{ .Values.hasura.metricsAdapter.image.pullPolicy }}
          env:
            - name: LOG_FILE
              value: /tmp/log/stdout.log
          volumeMounts:
          - name: logs
            mountPath: /tmp/log
          ports:
          - containerPort: 9090
            protocol: TCP
      volumes:
      - name: logs
        emptyDir: {}
      shareProcessNamespace: true
      {{- end }}
      {{- with .Values.hasura.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hasura.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hasura.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: bdjuno
