{{- $serviceName := include "hasura.fullname" . }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "hasura.fullname" . }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
  {{- with .Values.hasura.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.hasura.ingress.className }}
  {{- if .Values.hasura.ingress.tls }}
  tls:
    {{- range .Values.hasura.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.hasura.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}