apiVersion: v1
kind: Service
metadata:
  name: {{ include "hasura.fullname" . }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: {{ include "hasura.fullname" . }}
  selector:
    {{- include "hasura.selectorLabels" . | nindent 4 }}