# Default values for bdjuno.
# This is a YAML-formatted file.

# Spec for deploying bdjuno
bdjuno:
  ## Provide a name to substitute for the full names of resources
  ##
  nameOverride: ""
  fullnameOverride: ""
  replicaCount: 1

  image:
    repository: forbole/bdjuno
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []
  command: ["bdjuno", "start"]
  args: ['--home', '/bdjuno']

  podAnnotations: {}
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts: []
    tls: []
  resources: 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 500m
    #   memory: 5000Mi
    # requests:
    #   cpu: 100m
    #   memory: 500Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Spec for deploying bdjuno
hasura:  
  nameOverride: ""
  fullnameOverride: ""
  
  replicaCount: 1

  image:
    repository: hasura/graphql-engine
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v2.4.0"
  
  env: []

  podAnnotations:

  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts: []
    tls: []

  resources: 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 500m
    #   memory: 5000Mi
    # requests:
    #   cpu: 100m
    #   memory: 500Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  metricsAdapter:
    enabled: false
    image:
      repository: ghcr.io/afitzek/hasura-metric-adapter
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v0.2.0"